// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/privutil.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataFormat int32

const (
	DataFormat_JSON DataFormat = 0
	DataFormat_YAML DataFormat = 1
	DataFormat_XML  DataFormat = 2
)

// Enum value maps for DataFormat.
var (
	DataFormat_name = map[int32]string{
		0: "JSON",
		1: "YAML",
		2: "XML",
	}
	DataFormat_value = map[string]int32{
		"JSON": 0,
		"YAML": 1,
		"XML":  2,
	}
)

func (x DataFormat) Enum() *DataFormat {
	p := new(DataFormat)
	*p = x
	return p
}

func (x DataFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_privutil_proto_enumTypes[0].Descriptor()
}

func (DataFormat) Type() protoreflect.EnumType {
	return &file_proto_privutil_proto_enumTypes[0]
}

func (x DataFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataFormat.Descriptor instead.
func (DataFormat) EnumDescriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{0}
}

type TextAction int32

const (
	TextAction_SORT_AZ      TextAction = 0
	TextAction_SORT_ZA      TextAction = 1
	TextAction_SORT_NUMERIC TextAction = 2
	TextAction_REVERSE      TextAction = 3
	TextAction_DEDUPE       TextAction = 4
	TextAction_REMOVE_EMPTY TextAction = 5
	TextAction_TRIM         TextAction = 6
)

// Enum value maps for TextAction.
var (
	TextAction_name = map[int32]string{
		0: "SORT_AZ",
		1: "SORT_ZA",
		2: "SORT_NUMERIC",
		3: "REVERSE",
		4: "DEDUPE",
		5: "REMOVE_EMPTY",
		6: "TRIM",
	}
	TextAction_value = map[string]int32{
		"SORT_AZ":      0,
		"SORT_ZA":      1,
		"SORT_NUMERIC": 2,
		"REVERSE":      3,
		"DEDUPE":       4,
		"REMOVE_EMPTY": 5,
		"TRIM":         6,
	}
)

func (x TextAction) Enum() *TextAction {
	p := new(TextAction)
	*p = x
	return p
}

func (x TextAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TextAction) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_privutil_proto_enumTypes[1].Descriptor()
}

func (TextAction) Type() protoreflect.EnumType {
	return &file_proto_privutil_proto_enumTypes[1]
}

func (x TextAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TextAction.Descriptor instead.
func (TextAction) EnumDescriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{1}
}

type DiffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text1         string                 `protobuf:"bytes,1,opt,name=text1,proto3" json:"text1,omitempty"`
	Text2         string                 `protobuf:"bytes,2,opt,name=text2,proto3" json:"text2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffRequest) Reset() {
	*x = DiffRequest{}
	mi := &file_proto_privutil_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffRequest) ProtoMessage() {}

func (x *DiffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffRequest.ProtoReflect.Descriptor instead.
func (*DiffRequest) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{0}
}

func (x *DiffRequest) GetText1() string {
	if x != nil {
		return x.Text1
	}
	return ""
}

func (x *DiffRequest) GetText2() string {
	if x != nil {
		return x.Text2
	}
	return ""
}

type DiffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiffHtml      string                 `protobuf:"bytes,1,opt,name=diff_html,json=diffHtml,proto3" json:"diff_html,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffResponse) Reset() {
	*x = DiffResponse{}
	mi := &file_proto_privutil_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffResponse) ProtoMessage() {}

func (x *DiffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffResponse.ProtoReflect.Descriptor instead.
func (*DiffResponse) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{1}
}

func (x *DiffResponse) GetDiffHtml() string {
	if x != nil {
		return x.DiffHtml
	}
	return ""
}

type Base64Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Base64Request) Reset() {
	*x = Base64Request{}
	mi := &file_proto_privutil_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Base64Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Base64Request) ProtoMessage() {}

func (x *Base64Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Base64Request.ProtoReflect.Descriptor instead.
func (*Base64Request) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{2}
}

func (x *Base64Request) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Base64Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Base64Response) Reset() {
	*x = Base64Response{}
	mi := &file_proto_privutil_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Base64Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Base64Response) ProtoMessage() {}

func (x *Base64Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Base64Response.ProtoReflect.Descriptor instead.
func (*Base64Response) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{3}
}

func (x *Base64Response) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Base64Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type JsonFormatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Indent        string                 `protobuf:"bytes,2,opt,name=indent,proto3" json:"indent,omitempty"` // "2", "4", "tab", or "min" (minify)
	SortKeys      bool                   `protobuf:"varint,3,opt,name=sort_keys,json=sortKeys,proto3" json:"sort_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JsonFormatRequest) Reset() {
	*x = JsonFormatRequest{}
	mi := &file_proto_privutil_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsonFormatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonFormatRequest) ProtoMessage() {}

func (x *JsonFormatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonFormatRequest.ProtoReflect.Descriptor instead.
func (*JsonFormatRequest) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{4}
}

func (x *JsonFormatRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *JsonFormatRequest) GetIndent() string {
	if x != nil {
		return x.Indent
	}
	return ""
}

func (x *JsonFormatRequest) GetSortKeys() bool {
	if x != nil {
		return x.SortKeys
	}
	return false
}

type JsonFormatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JsonFormatResponse) Reset() {
	*x = JsonFormatResponse{}
	mi := &file_proto_privutil_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsonFormatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonFormatResponse) ProtoMessage() {}

func (x *JsonFormatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonFormatResponse.ProtoReflect.Descriptor instead.
func (*JsonFormatResponse) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{5}
}

func (x *JsonFormatResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *JsonFormatResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ConvertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	SourceFormat  DataFormat             `protobuf:"varint,2,opt,name=source_format,json=sourceFormat,proto3,enum=privutil.DataFormat" json:"source_format,omitempty"`
	TargetFormat  DataFormat             `protobuf:"varint,3,opt,name=target_format,json=targetFormat,proto3,enum=privutil.DataFormat" json:"target_format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertRequest) Reset() {
	*x = ConvertRequest{}
	mi := &file_proto_privutil_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertRequest) ProtoMessage() {}

func (x *ConvertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertRequest.ProtoReflect.Descriptor instead.
func (*ConvertRequest) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{6}
}

func (x *ConvertRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *ConvertRequest) GetSourceFormat() DataFormat {
	if x != nil {
		return x.SourceFormat
	}
	return DataFormat_JSON
}

func (x *ConvertRequest) GetTargetFormat() DataFormat {
	if x != nil {
		return x.TargetFormat
	}
	return DataFormat_JSON
}

type ConvertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertResponse) Reset() {
	*x = ConvertResponse{}
	mi := &file_proto_privutil_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertResponse) ProtoMessage() {}

func (x *ConvertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertResponse.ProtoReflect.Descriptor instead.
func (*ConvertResponse) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{7}
}

func (x *ConvertResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *ConvertResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UuidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hyphen        bool                   `protobuf:"varint,1,opt,name=hyphen,proto3" json:"hyphen,omitempty"`
	Uppercase     bool                   `protobuf:"varint,2,opt,name=uppercase,proto3" json:"uppercase,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`     // "v1", "v2", "v3", "v4", "v5", "v6", "v7", "v8"
	Namespace     string                 `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"` // For v3, v5, v8: "dns", "url", "oid", "x500" (default: "dns")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UuidRequest) Reset() {
	*x = UuidRequest{}
	mi := &file_proto_privutil_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UuidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UuidRequest) ProtoMessage() {}

func (x *UuidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UuidRequest.ProtoReflect.Descriptor instead.
func (*UuidRequest) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{8}
}

func (x *UuidRequest) GetHyphen() bool {
	if x != nil {
		return x.Hyphen
	}
	return false
}

func (x *UuidRequest) GetUppercase() bool {
	if x != nil {
		return x.Uppercase
	}
	return false
}

func (x *UuidRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *UuidRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UuidRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type UuidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuids         []string               `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UuidResponse) Reset() {
	*x = UuidResponse{}
	mi := &file_proto_privutil_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UuidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UuidResponse) ProtoMessage() {}

func (x *UuidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UuidResponse.ProtoReflect.Descriptor instead.
func (*UuidResponse) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{9}
}

func (x *UuidResponse) GetUuids() []string {
	if x != nil {
		return x.Uuids
	}
	return nil
}

type LoremRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "word", "sentence", "paragraph"
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoremRequest) Reset() {
	*x = LoremRequest{}
	mi := &file_proto_privutil_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoremRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoremRequest) ProtoMessage() {}

func (x *LoremRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoremRequest.ProtoReflect.Descriptor instead.
func (*LoremRequest) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{10}
}

func (x *LoremRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LoremRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type LoremResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoremResponse) Reset() {
	*x = LoremResponse{}
	mi := &file_proto_privutil_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoremResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoremResponse) ProtoMessage() {}

func (x *LoremResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoremResponse.ProtoReflect.Descriptor instead.
func (*LoremResponse) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{11}
}

func (x *LoremResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type HashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Algo          string                 `protobuf:"bytes,2,opt,name=algo,proto3" json:"algo,omitempty"` // "md5", "sha1", "sha256", "sha512"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashRequest) Reset() {
	*x = HashRequest{}
	mi := &file_proto_privutil_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashRequest) ProtoMessage() {}

func (x *HashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashRequest.ProtoReflect.Descriptor instead.
func (*HashRequest) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{12}
}

func (x *HashRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *HashRequest) GetAlgo() string {
	if x != nil {
		return x.Algo
	}
	return ""
}

type HashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashResponse) Reset() {
	*x = HashResponse{}
	mi := &file_proto_privutil_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashResponse) ProtoMessage() {}

func (x *HashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashResponse.ProtoReflect.Descriptor instead.
func (*HashResponse) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{13}
}

func (x *HashResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type TextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextRequest) Reset() {
	*x = TextRequest{}
	mi := &file_proto_privutil_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextRequest) ProtoMessage() {}

func (x *TextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextRequest.ProtoReflect.Descriptor instead.
func (*TextRequest) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{14}
}

func (x *TextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextResponse) Reset() {
	*x = TextResponse{}
	mi := &file_proto_privutil_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextResponse) ProtoMessage() {}

func (x *TextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextResponse.ProtoReflect.Descriptor instead.
func (*TextResponse) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{15}
}

func (x *TextResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"` // Can be timestamp (int string) or ISO date
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRequest) Reset() {
	*x = TimeRequest{}
	mi := &file_proto_privutil_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRequest) ProtoMessage() {}

func (x *TimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRequest.ProtoReflect.Descriptor instead.
func (*TimeRequest) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{16}
}

func (x *TimeRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type TimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unix          int64                  `protobuf:"varint,1,opt,name=unix,proto3" json:"unix,omitempty"`
	Utc           string                 `protobuf:"bytes,2,opt,name=utc,proto3" json:"utc,omitempty"`
	Local         string                 `protobuf:"bytes,3,opt,name=local,proto3" json:"local,omitempty"`
	Iso           string                 `protobuf:"bytes,4,opt,name=iso,proto3" json:"iso,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeResponse) Reset() {
	*x = TimeResponse{}
	mi := &file_proto_privutil_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeResponse) ProtoMessage() {}

func (x *TimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeResponse.ProtoReflect.Descriptor instead.
func (*TimeResponse) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{17}
}

func (x *TimeResponse) GetUnix() int64 {
	if x != nil {
		return x.Unix
	}
	return 0
}

func (x *TimeResponse) GetUtc() string {
	if x != nil {
		return x.Utc
	}
	return ""
}

func (x *TimeResponse) GetLocal() string {
	if x != nil {
		return x.Local
	}
	return ""
}

func (x *TimeResponse) GetIso() string {
	if x != nil {
		return x.Iso
	}
	return ""
}

type JwtRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwtRequest) Reset() {
	*x = JwtRequest{}
	mi := &file_proto_privutil_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtRequest) ProtoMessage() {}

func (x *JwtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtRequest.ProtoReflect.Descriptor instead.
func (*JwtRequest) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{18}
}

func (x *JwtRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type JwtResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        string                 `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwtResponse) Reset() {
	*x = JwtResponse{}
	mi := &file_proto_privutil_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwtResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtResponse) ProtoMessage() {}

func (x *JwtResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtResponse.ProtoReflect.Descriptor instead.
func (*JwtResponse) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{19}
}

func (x *JwtResponse) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *JwtResponse) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *JwtResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RegexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pattern       string                 `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegexRequest) Reset() {
	*x = RegexRequest{}
	mi := &file_proto_privutil_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegexRequest) ProtoMessage() {}

func (x *RegexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegexRequest.ProtoReflect.Descriptor instead.
func (*RegexRequest) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{20}
}

func (x *RegexRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *RegexRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type RegexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match         bool                   `protobuf:"varint,1,opt,name=match,proto3" json:"match,omitempty"`
	Matches       []string               `protobuf:"bytes,2,rep,name=matches,proto3" json:"matches,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegexResponse) Reset() {
	*x = RegexResponse{}
	mi := &file_proto_privutil_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegexResponse) ProtoMessage() {}

func (x *RegexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegexResponse.ProtoReflect.Descriptor instead.
func (*RegexResponse) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{21}
}

func (x *RegexResponse) GetMatch() bool {
	if x != nil {
		return x.Match
	}
	return false
}

func (x *RegexResponse) GetMatches() []string {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *RegexResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type JsonToGoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	StructName    string                 `protobuf:"bytes,2,opt,name=struct_name,json=structName,proto3" json:"struct_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JsonToGoRequest) Reset() {
	*x = JsonToGoRequest{}
	mi := &file_proto_privutil_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsonToGoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonToGoRequest) ProtoMessage() {}

func (x *JsonToGoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonToGoRequest.ProtoReflect.Descriptor instead.
func (*JsonToGoRequest) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{22}
}

func (x *JsonToGoRequest) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

func (x *JsonToGoRequest) GetStructName() string {
	if x != nil {
		return x.StructName
	}
	return ""
}

type JsonToGoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoCode        string                 `protobuf:"bytes,1,opt,name=go_code,json=goCode,proto3" json:"go_code,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JsonToGoResponse) Reset() {
	*x = JsonToGoResponse{}
	mi := &file_proto_privutil_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsonToGoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonToGoResponse) ProtoMessage() {}

func (x *JsonToGoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonToGoResponse.ProtoReflect.Descriptor instead.
func (*JsonToGoResponse) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{23}
}

func (x *JsonToGoResponse) GetGoCode() string {
	if x != nil {
		return x.GoCode
	}
	return ""
}

func (x *JsonToGoResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CronRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expression    string                 `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronRequest) Reset() {
	*x = CronRequest{}
	mi := &file_proto_privutil_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronRequest) ProtoMessage() {}

func (x *CronRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronRequest.ProtoReflect.Descriptor instead.
func (*CronRequest) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{24}
}

func (x *CronRequest) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

type CronResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	NextRuns      string                 `protobuf:"bytes,2,opt,name=next_runs,json=nextRuns,proto3" json:"next_runs,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronResponse) Reset() {
	*x = CronResponse{}
	mi := &file_proto_privutil_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronResponse) ProtoMessage() {}

func (x *CronResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronResponse.ProtoReflect.Descriptor instead.
func (*CronResponse) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{25}
}

func (x *CronResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CronResponse) GetNextRuns() string {
	if x != nil {
		return x.NextRuns
	}
	return ""
}

func (x *CronResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // PEM
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertRequest) Reset() {
	*x = CertRequest{}
	mi := &file_proto_privutil_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertRequest) ProtoMessage() {}

func (x *CertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertRequest.ProtoReflect.Descriptor instead.
func (*CertRequest) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{26}
}

func (x *CertRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type CertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Issuer        string                 `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	NotBefore     string                 `protobuf:"bytes,3,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter      string                 `protobuf:"bytes,4,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	Sans          []string               `protobuf:"bytes,5,rep,name=sans,proto3" json:"sans,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertResponse) Reset() {
	*x = CertResponse{}
	mi := &file_proto_privutil_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertResponse) ProtoMessage() {}

func (x *CertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertResponse.ProtoReflect.Descriptor instead.
func (*CertResponse) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{27}
}

func (x *CertResponse) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CertResponse) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *CertResponse) GetNotBefore() string {
	if x != nil {
		return x.NotBefore
	}
	return ""
}

func (x *CertResponse) GetNotAfter() string {
	if x != nil {
		return x.NotAfter
	}
	return ""
}

func (x *CertResponse) GetSans() []string {
	if x != nil {
		return x.Sans
	}
	return nil
}

func (x *CertResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ColorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"` // Any format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColorRequest) Reset() {
	*x = ColorRequest{}
	mi := &file_proto_privutil_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorRequest) ProtoMessage() {}

func (x *ColorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorRequest.ProtoReflect.Descriptor instead.
func (*ColorRequest) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{28}
}

func (x *ColorRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type ColorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hex           string                 `protobuf:"bytes,1,opt,name=hex,proto3" json:"hex,omitempty"`
	Rgb           string                 `protobuf:"bytes,2,opt,name=rgb,proto3" json:"rgb,omitempty"`
	Hsl           string                 `protobuf:"bytes,3,opt,name=hsl,proto3" json:"hsl,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColorResponse) Reset() {
	*x = ColorResponse{}
	mi := &file_proto_privutil_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorResponse) ProtoMessage() {}

func (x *ColorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorResponse.ProtoReflect.Descriptor instead.
func (*ColorResponse) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{29}
}

func (x *ColorResponse) GetHex() string {
	if x != nil {
		return x.Hex
	}
	return ""
}

func (x *ColorResponse) GetRgb() string {
	if x != nil {
		return x.Rgb
	}
	return ""
}

func (x *ColorResponse) GetHsl() string {
	if x != nil {
		return x.Hsl
	}
	return ""
}

func (x *ColorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaseRequest) Reset() {
	*x = CaseRequest{}
	mi := &file_proto_privutil_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaseRequest) ProtoMessage() {}

func (x *CaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaseRequest.ProtoReflect.Descriptor instead.
func (*CaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{30}
}

func (x *CaseRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type CaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Camel         string                 `protobuf:"bytes,1,opt,name=camel,proto3" json:"camel,omitempty"`
	Snake         string                 `protobuf:"bytes,2,opt,name=snake,proto3" json:"snake,omitempty"`
	Pascal        string                 `protobuf:"bytes,3,opt,name=pascal,proto3" json:"pascal,omitempty"`
	Kebab         string                 `protobuf:"bytes,4,opt,name=kebab,proto3" json:"kebab,omitempty"`
	Constant      string                 `protobuf:"bytes,5,opt,name=constant,proto3" json:"constant,omitempty"` // UPPER_SNAKE_CASE
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaseResponse) Reset() {
	*x = CaseResponse{}
	mi := &file_proto_privutil_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaseResponse) ProtoMessage() {}

func (x *CaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaseResponse.ProtoReflect.Descriptor instead.
func (*CaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{31}
}

func (x *CaseResponse) GetCamel() string {
	if x != nil {
		return x.Camel
	}
	return ""
}

func (x *CaseResponse) GetSnake() string {
	if x != nil {
		return x.Snake
	}
	return ""
}

func (x *CaseResponse) GetPascal() string {
	if x != nil {
		return x.Pascal
	}
	return ""
}

func (x *CaseResponse) GetKebab() string {
	if x != nil {
		return x.Kebab
	}
	return ""
}

func (x *CaseResponse) GetConstant() string {
	if x != nil {
		return x.Constant
	}
	return ""
}

func (x *CaseResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CaseResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type EscapeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`     // "json", "java", "sql", "html_entity"
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"` // "escape", "unescape"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EscapeRequest) Reset() {
	*x = EscapeRequest{}
	mi := &file_proto_privutil_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EscapeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscapeRequest) ProtoMessage() {}

func (x *EscapeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscapeRequest.ProtoReflect.Descriptor instead.
func (*EscapeRequest) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{32}
}

func (x *EscapeRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *EscapeRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *EscapeRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type EscapeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EscapeResponse) Reset() {
	*x = EscapeResponse{}
	mi := &file_proto_privutil_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EscapeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscapeResponse) ProtoMessage() {}

func (x *EscapeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscapeResponse.ProtoReflect.Descriptor instead.
func (*EscapeResponse) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{33}
}

func (x *EscapeResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *EscapeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SimilarityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text1         string                 `protobuf:"bytes,1,opt,name=text1,proto3" json:"text1,omitempty"`
	Text2         string                 `protobuf:"bytes,2,opt,name=text2,proto3" json:"text2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimilarityRequest) Reset() {
	*x = SimilarityRequest{}
	mi := &file_proto_privutil_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimilarityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimilarityRequest) ProtoMessage() {}

func (x *SimilarityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimilarityRequest.ProtoReflect.Descriptor instead.
func (*SimilarityRequest) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{34}
}

func (x *SimilarityRequest) GetText1() string {
	if x != nil {
		return x.Text1
	}
	return ""
}

func (x *SimilarityRequest) GetText2() string {
	if x != nil {
		return x.Text2
	}
	return ""
}

type SimilarityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Distance      int32                  `protobuf:"varint,1,opt,name=distance,proto3" json:"distance,omitempty"`
	Similarity    float32                `protobuf:"fixed32,2,opt,name=similarity,proto3" json:"similarity,omitempty"` // 0.0 to 1.0
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimilarityResponse) Reset() {
	*x = SimilarityResponse{}
	mi := &file_proto_privutil_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimilarityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimilarityResponse) ProtoMessage() {}

func (x *SimilarityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimilarityResponse.ProtoReflect.Descriptor instead.
func (*SimilarityResponse) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{35}
}

func (x *SimilarityResponse) GetDistance() int32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *SimilarityResponse) GetSimilarity() float32 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

func (x *SimilarityResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SqlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SqlRequest) Reset() {
	*x = SqlRequest{}
	mi := &file_proto_privutil_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SqlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SqlRequest) ProtoMessage() {}

func (x *SqlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SqlRequest.ProtoReflect.Descriptor instead.
func (*SqlRequest) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{36}
}

func (x *SqlRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SqlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Formatted     string                 `protobuf:"bytes,1,opt,name=formatted,proto3" json:"formatted,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SqlResponse) Reset() {
	*x = SqlResponse{}
	mi := &file_proto_privutil_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SqlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SqlResponse) ProtoMessage() {}

func (x *SqlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SqlResponse.ProtoReflect.Descriptor instead.
func (*SqlResponse) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{37}
}

func (x *SqlResponse) GetFormatted() string {
	if x != nil {
		return x.Formatted
	}
	return ""
}

func (x *SqlResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type IpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpRequest) Reset() {
	*x = IpRequest{}
	mi := &file_proto_privutil_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpRequest) ProtoMessage() {}

func (x *IpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpRequest.ProtoReflect.Descriptor instead.
func (*IpRequest) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{38}
}

func (x *IpRequest) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

type IpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Broadcast     string                 `protobuf:"bytes,2,opt,name=broadcast,proto3" json:"broadcast,omitempty"`
	Netmask       string                 `protobuf:"bytes,3,opt,name=netmask,proto3" json:"netmask,omitempty"`
	FirstIp       string                 `protobuf:"bytes,4,opt,name=first_ip,json=firstIp,proto3" json:"first_ip,omitempty"`
	LastIp        string                 `protobuf:"bytes,5,opt,name=last_ip,json=lastIp,proto3" json:"last_ip,omitempty"`
	NumHosts      int64                  `protobuf:"varint,6,opt,name=num_hosts,json=numHosts,proto3" json:"num_hosts,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpResponse) Reset() {
	*x = IpResponse{}
	mi := &file_proto_privutil_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpResponse) ProtoMessage() {}

func (x *IpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpResponse.ProtoReflect.Descriptor instead.
func (*IpResponse) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{39}
}

func (x *IpResponse) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *IpResponse) GetBroadcast() string {
	if x != nil {
		return x.Broadcast
	}
	return ""
}

func (x *IpResponse) GetNetmask() string {
	if x != nil {
		return x.Netmask
	}
	return ""
}

func (x *IpResponse) GetFirstIp() string {
	if x != nil {
		return x.FirstIp
	}
	return ""
}

func (x *IpResponse) GetLastIp() string {
	if x != nil {
		return x.LastIp
	}
	return ""
}

func (x *IpResponse) GetNumHosts() int64 {
	if x != nil {
		return x.NumHosts
	}
	return 0
}

func (x *IpResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TextInspectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextInspectRequest) Reset() {
	*x = TextInspectRequest{}
	mi := &file_proto_privutil_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextInspectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextInspectRequest) ProtoMessage() {}

func (x *TextInspectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextInspectRequest.ProtoReflect.Descriptor instead.
func (*TextInspectRequest) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{40}
}

func (x *TextInspectRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TextInspectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharCount     int32                  `protobuf:"varint,1,opt,name=char_count,json=charCount,proto3" json:"char_count,omitempty"`
	WordCount     int32                  `protobuf:"varint,2,opt,name=word_count,json=wordCount,proto3" json:"word_count,omitempty"`
	LineCount     int32                  `protobuf:"varint,3,opt,name=line_count,json=lineCount,proto3" json:"line_count,omitempty"`
	ByteCount     int32                  `protobuf:"varint,4,opt,name=byte_count,json=byteCount,proto3" json:"byte_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextInspectResponse) Reset() {
	*x = TextInspectResponse{}
	mi := &file_proto_privutil_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextInspectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextInspectResponse) ProtoMessage() {}

func (x *TextInspectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextInspectResponse.ProtoReflect.Descriptor instead.
func (*TextInspectResponse) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{41}
}

func (x *TextInspectResponse) GetCharCount() int32 {
	if x != nil {
		return x.CharCount
	}
	return 0
}

func (x *TextInspectResponse) GetWordCount() int32 {
	if x != nil {
		return x.WordCount
	}
	return 0
}

func (x *TextInspectResponse) GetLineCount() int32 {
	if x != nil {
		return x.LineCount
	}
	return 0
}

func (x *TextInspectResponse) GetByteCount() int32 {
	if x != nil {
		return x.ByteCount
	}
	return 0
}

type TextManipulateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Action        TextAction             `protobuf:"varint,2,opt,name=action,proto3,enum=privutil.TextAction" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextManipulateRequest) Reset() {
	*x = TextManipulateRequest{}
	mi := &file_proto_privutil_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextManipulateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextManipulateRequest) ProtoMessage() {}

func (x *TextManipulateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextManipulateRequest.ProtoReflect.Descriptor instead.
func (*TextManipulateRequest) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{42}
}

func (x *TextManipulateRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextManipulateRequest) GetAction() TextAction {
	if x != nil {
		return x.Action
	}
	return TextAction_SORT_AZ
}

type TextManipulateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextManipulateResponse) Reset() {
	*x = TextManipulateResponse{}
	mi := &file_proto_privutil_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextManipulateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextManipulateResponse) ProtoMessage() {}

func (x *TextManipulateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextManipulateResponse.ProtoReflect.Descriptor instead.
func (*TextManipulateResponse) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{43}
}

func (x *TextManipulateResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type PasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Length        int32                  `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	Uppercase     bool                   `protobuf:"varint,2,opt,name=uppercase,proto3" json:"uppercase,omitempty"`
	Lowercase     bool                   `protobuf:"varint,3,opt,name=lowercase,proto3" json:"lowercase,omitempty"`
	Numbers       bool                   `protobuf:"varint,4,opt,name=numbers,proto3" json:"numbers,omitempty"`
	Symbols       bool                   `protobuf:"varint,5,opt,name=symbols,proto3" json:"symbols,omitempty"`
	CustomChars   string                 `protobuf:"bytes,6,opt,name=custom_chars,json=customChars,proto3" json:"custom_chars,omitempty"` // Custom character set to use
	Count         int32                  `protobuf:"varint,7,opt,name=count,proto3" json:"count,omitempty"`                               // Number of passwords to generate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordRequest) Reset() {
	*x = PasswordRequest{}
	mi := &file_proto_privutil_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordRequest) ProtoMessage() {}

func (x *PasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordRequest.ProtoReflect.Descriptor instead.
func (*PasswordRequest) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{44}
}

func (x *PasswordRequest) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *PasswordRequest) GetUppercase() bool {
	if x != nil {
		return x.Uppercase
	}
	return false
}

func (x *PasswordRequest) GetLowercase() bool {
	if x != nil {
		return x.Lowercase
	}
	return false
}

func (x *PasswordRequest) GetNumbers() bool {
	if x != nil {
		return x.Numbers
	}
	return false
}

func (x *PasswordRequest) GetSymbols() bool {
	if x != nil {
		return x.Symbols
	}
	return false
}

func (x *PasswordRequest) GetCustomChars() string {
	if x != nil {
		return x.CustomChars
	}
	return ""
}

func (x *PasswordRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type PasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Passwords     []string               `protobuf:"bytes,1,rep,name=passwords,proto3" json:"passwords,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordResponse) Reset() {
	*x = PasswordResponse{}
	mi := &file_proto_privutil_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordResponse) ProtoMessage() {}

func (x *PasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privutil_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordResponse.ProtoReflect.Descriptor instead.
func (*PasswordResponse) Descriptor() ([]byte, []int) {
	return file_proto_privutil_proto_rawDescGZIP(), []int{45}
}

func (x *PasswordResponse) GetPasswords() []string {
	if x != nil {
		return x.Passwords
	}
	return nil
}

func (x *PasswordResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_privutil_proto protoreflect.FileDescriptor

const file_proto_privutil_proto_rawDesc = "" +
	"\n" +
	"\x14proto/privutil.proto\x12\bprivutil\"9\n" +
	"\vDiffRequest\x12\x14\n" +
	"\x05text1\x18\x01 \x01(\tR\x05text1\x12\x14\n" +
	"\x05text2\x18\x02 \x01(\tR\x05text2\"+\n" +
	"\fDiffResponse\x12\x1b\n" +
	"\tdiff_html\x18\x01 \x01(\tR\bdiffHtml\"#\n" +
	"\rBase64Request\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\":\n" +
	"\x0eBase64Response\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\\\n" +
	"\x11JsonFormatRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x16\n" +
	"\x06indent\x18\x02 \x01(\tR\x06indent\x12\x1b\n" +
	"\tsort_keys\x18\x03 \x01(\bR\bsortKeys\">\n" +
	"\x12JsonFormatResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x9a\x01\n" +
	"\x0eConvertRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x129\n" +
	"\rsource_format\x18\x02 \x01(\x0e2\x14.privutil.DataFormatR\fsourceFormat\x129\n" +
	"\rtarget_format\x18\x03 \x01(\x0e2\x14.privutil.DataFormatR\ftargetFormat\";\n" +
	"\x0fConvertResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x91\x01\n" +
	"\vUuidRequest\x12\x16\n" +
	"\x06hyphen\x18\x01 \x01(\bR\x06hyphen\x12\x1c\n" +
	"\tuppercase\x18\x02 \x01(\bR\tuppercase\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\"$\n" +
	"\fUuidResponse\x12\x14\n" +
	"\x05uuids\x18\x01 \x03(\tR\x05uuids\"8\n" +
	"\fLoremRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"#\n" +
	"\rLoremResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"5\n" +
	"\vHashRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x12\n" +
	"\x04algo\x18\x02 \x01(\tR\x04algo\"\"\n" +
	"\fHashResponse\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"!\n" +
	"\vTextRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\"\n" +
	"\fTextResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"#\n" +
	"\vTimeRequest\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\"\\\n" +
	"\fTimeResponse\x12\x12\n" +
	"\x04unix\x18\x01 \x01(\x03R\x04unix\x12\x10\n" +
	"\x03utc\x18\x02 \x01(\tR\x03utc\x12\x14\n" +
	"\x05local\x18\x03 \x01(\tR\x05local\x12\x10\n" +
	"\x03iso\x18\x04 \x01(\tR\x03iso\"\"\n" +
	"\n" +
	"JwtRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"U\n" +
	"\vJwtResponse\x12\x16\n" +
	"\x06header\x18\x01 \x01(\tR\x06header\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"<\n" +
	"\fRegexRequest\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"U\n" +
	"\rRegexResponse\x12\x14\n" +
	"\x05match\x18\x01 \x01(\bR\x05match\x12\x18\n" +
	"\amatches\x18\x02 \x03(\tR\amatches\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"F\n" +
	"\x0fJsonToGoRequest\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json\x12\x1f\n" +
	"\vstruct_name\x18\x02 \x01(\tR\n" +
	"structName\"A\n" +
	"\x10JsonToGoResponse\x12\x17\n" +
	"\ago_code\x18\x01 \x01(\tR\x06goCode\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"-\n" +
	"\vCronRequest\x12\x1e\n" +
	"\n" +
	"expression\x18\x01 \x01(\tR\n" +
	"expression\"c\n" +
	"\fCronResponse\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x1b\n" +
	"\tnext_runs\x18\x02 \x01(\tR\bnextRuns\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"!\n" +
	"\vCertRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"\xa6\x01\n" +
	"\fCertResponse\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x12\x1d\n" +
	"\n" +
	"not_before\x18\x03 \x01(\tR\tnotBefore\x12\x1b\n" +
	"\tnot_after\x18\x04 \x01(\tR\bnotAfter\x12\x12\n" +
	"\x04sans\x18\x05 \x03(\tR\x04sans\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"$\n" +
	"\fColorRequest\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\"[\n" +
	"\rColorResponse\x12\x10\n" +
	"\x03hex\x18\x01 \x01(\tR\x03hex\x12\x10\n" +
	"\x03rgb\x18\x02 \x01(\tR\x03rgb\x12\x10\n" +
	"\x03hsl\x18\x03 \x01(\tR\x03hsl\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"!\n" +
	"\vCaseRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\xb0\x01\n" +
	"\fCaseResponse\x12\x14\n" +
	"\x05camel\x18\x01 \x01(\tR\x05camel\x12\x14\n" +
	"\x05snake\x18\x02 \x01(\tR\x05snake\x12\x16\n" +
	"\x06pascal\x18\x03 \x01(\tR\x06pascal\x12\x14\n" +
	"\x05kebab\x18\x04 \x01(\tR\x05kebab\x12\x1a\n" +
	"\bconstant\x18\x05 \x01(\tR\bconstant\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"O\n" +
	"\rEscapeRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\">\n" +
	"\x0eEscapeResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"?\n" +
	"\x11SimilarityRequest\x12\x14\n" +
	"\x05text1\x18\x01 \x01(\tR\x05text1\x12\x14\n" +
	"\x05text2\x18\x02 \x01(\tR\x05text2\"f\n" +
	"\x12SimilarityResponse\x12\x1a\n" +
	"\bdistance\x18\x01 \x01(\x05R\bdistance\x12\x1e\n" +
	"\n" +
	"similarity\x18\x02 \x01(\x02R\n" +
	"similarity\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\"\n" +
	"\n" +
	"SqlRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"A\n" +
	"\vSqlResponse\x12\x1c\n" +
	"\tformatted\x18\x01 \x01(\tR\tformatted\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x1f\n" +
	"\tIpRequest\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\"\xc5\x01\n" +
	"\n" +
	"IpResponse\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x1c\n" +
	"\tbroadcast\x18\x02 \x01(\tR\tbroadcast\x12\x18\n" +
	"\anetmask\x18\x03 \x01(\tR\anetmask\x12\x19\n" +
	"\bfirst_ip\x18\x04 \x01(\tR\afirstIp\x12\x17\n" +
	"\alast_ip\x18\x05 \x01(\tR\x06lastIp\x12\x1b\n" +
	"\tnum_hosts\x18\x06 \x01(\x03R\bnumHosts\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"(\n" +
	"\x12TextInspectRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\x91\x01\n" +
	"\x13TextInspectResponse\x12\x1d\n" +
	"\n" +
	"char_count\x18\x01 \x01(\x05R\tcharCount\x12\x1d\n" +
	"\n" +
	"word_count\x18\x02 \x01(\x05R\twordCount\x12\x1d\n" +
	"\n" +
	"line_count\x18\x03 \x01(\x05R\tlineCount\x12\x1d\n" +
	"\n" +
	"byte_count\x18\x04 \x01(\x05R\tbyteCount\"Y\n" +
	"\x15TextManipulateRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12,\n" +
	"\x06action\x18\x02 \x01(\x0e2\x14.privutil.TextActionR\x06action\",\n" +
	"\x16TextManipulateResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\xd2\x01\n" +
	"\x0fPasswordRequest\x12\x16\n" +
	"\x06length\x18\x01 \x01(\x05R\x06length\x12\x1c\n" +
	"\tuppercase\x18\x02 \x01(\bR\tuppercase\x12\x1c\n" +
	"\tlowercase\x18\x03 \x01(\bR\tlowercase\x12\x18\n" +
	"\anumbers\x18\x04 \x01(\bR\anumbers\x12\x18\n" +
	"\asymbols\x18\x05 \x01(\bR\asymbols\x12!\n" +
	"\fcustom_chars\x18\x06 \x01(\tR\vcustomChars\x12\x14\n" +
	"\x05count\x18\a \x01(\x05R\x05count\"F\n" +
	"\x10PasswordResponse\x12\x1c\n" +
	"\tpasswords\x18\x01 \x03(\tR\tpasswords\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error*)\n" +
	"\n" +
	"DataFormat\x12\b\n" +
	"\x04JSON\x10\x00\x12\b\n" +
	"\x04YAML\x10\x01\x12\a\n" +
	"\x03XML\x10\x02*m\n" +
	"\n" +
	"TextAction\x12\v\n" +
	"\aSORT_AZ\x10\x00\x12\v\n" +
	"\aSORT_ZA\x10\x01\x12\x10\n" +
	"\fSORT_NUMERIC\x10\x02\x12\v\n" +
	"\aREVERSE\x10\x03\x12\n" +
	"\n" +
	"\x06DEDUPE\x10\x04\x12\x10\n" +
	"\fREMOVE_EMPTY\x10\x05\x12\b\n" +
	"\x04TRIM\x10\x062\x9d\x0e\n" +
	"\x0fPrivUtilService\x127\n" +
	"\x04Diff\x12\x15.privutil.DiffRequest\x1a\x16.privutil.DiffResponse\"\x00\x12C\n" +
	"\fBase64Encode\x12\x17.privutil.Base64Request\x1a\x18.privutil.Base64Response\"\x00\x12C\n" +
	"\fBase64Decode\x12\x17.privutil.Base64Request\x1a\x18.privutil.Base64Response\"\x00\x12I\n" +
	"\n" +
	"JsonFormat\x12\x1b.privutil.JsonFormatRequest\x1a\x1c.privutil.JsonFormatResponse\"\x00\x12@\n" +
	"\aConvert\x12\x18.privutil.ConvertRequest\x1a\x19.privutil.ConvertResponse\"\x00\x12?\n" +
	"\fGenerateUuid\x12\x15.privutil.UuidRequest\x1a\x16.privutil.UuidResponse\"\x00\x12B\n" +
	"\rGenerateLorem\x12\x16.privutil.LoremRequest\x1a\x17.privutil.LoremResponse\"\x00\x12@\n" +
	"\rCalculateHash\x12\x15.privutil.HashRequest\x1a\x16.privutil.HashResponse\"\x00\x12L\n" +
	"\vTextInspect\x12\x1c.privutil.TextInspectRequest\x1a\x1d.privutil.TextInspectResponse\"\x00\x12U\n" +
	"\x0eTextManipulate\x12\x1f.privutil.TextManipulateRequest\x1a .privutil.TextManipulateResponse\"\x00\x12<\n" +
	"\tUrlEncode\x12\x15.privutil.TextRequest\x1a\x16.privutil.TextResponse\"\x00\x12<\n" +
	"\tUrlDecode\x12\x15.privutil.TextRequest\x1a\x16.privutil.TextResponse\"\x00\x12=\n" +
	"\n" +
	"HtmlEncode\x12\x15.privutil.TextRequest\x1a\x16.privutil.TextResponse\"\x00\x12=\n" +
	"\n" +
	"HtmlDecode\x12\x15.privutil.TextRequest\x1a\x16.privutil.TextResponse\"\x00\x12>\n" +
	"\vTimeConvert\x12\x15.privutil.TimeRequest\x1a\x16.privutil.TimeResponse\"\x00\x12:\n" +
	"\tJwtDecode\x12\x14.privutil.JwtRequest\x1a\x15.privutil.JwtResponse\"\x00\x12>\n" +
	"\tRegexTest\x12\x16.privutil.RegexRequest\x1a\x17.privutil.RegexResponse\"\x00\x12C\n" +
	"\bJsonToGo\x12\x19.privutil.JsonToGoRequest\x1a\x1a.privutil.JsonToGoResponse\"\x00\x12>\n" +
	"\vCronExplain\x12\x15.privutil.CronRequest\x1a\x16.privutil.CronResponse\"\x00\x12<\n" +
	"\tCertParse\x12\x15.privutil.CertRequest\x1a\x16.privutil.CertResponse\"\x00\x12A\n" +
	"\fColorConvert\x12\x16.privutil.ColorRequest\x1a\x17.privutil.ColorResponse\"\x00\x12>\n" +
	"\vCaseConvert\x12\x15.privutil.CaseRequest\x1a\x16.privutil.CaseResponse\"\x00\x12C\n" +
	"\fStringEscape\x12\x17.privutil.EscapeRequest\x1a\x18.privutil.EscapeResponse\"\x00\x12M\n" +
	"\x0eTextSimilarity\x12\x1b.privutil.SimilarityRequest\x1a\x1c.privutil.SimilarityResponse\"\x00\x12:\n" +
	"\tSqlFormat\x12\x14.privutil.SqlRequest\x1a\x15.privutil.SqlResponse\"\x00\x125\n" +
	"\x06IpCalc\x12\x13.privutil.IpRequest\x1a\x14.privutil.IpResponse\"\x00\x12K\n" +
	"\x10GeneratePassword\x12\x19.privutil.PasswordRequest\x1a\x1a.privutil.PasswordResponse\"\x00B'Z%github.com/odinnordico/privutil/protob\x06proto3"

var (
	file_proto_privutil_proto_rawDescOnce sync.Once
	file_proto_privutil_proto_rawDescData []byte
)

func file_proto_privutil_proto_rawDescGZIP() []byte {
	file_proto_privutil_proto_rawDescOnce.Do(func() {
		file_proto_privutil_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_privutil_proto_rawDesc), len(file_proto_privutil_proto_rawDesc)))
	})
	return file_proto_privutil_proto_rawDescData
}

var file_proto_privutil_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_privutil_proto_msgTypes = make([]protoimpl.MessageInfo, 46)
var file_proto_privutil_proto_goTypes = []any{
	(DataFormat)(0),                // 0: privutil.DataFormat
	(TextAction)(0),                // 1: privutil.TextAction
	(*DiffRequest)(nil),            // 2: privutil.DiffRequest
	(*DiffResponse)(nil),           // 3: privutil.DiffResponse
	(*Base64Request)(nil),          // 4: privutil.Base64Request
	(*Base64Response)(nil),         // 5: privutil.Base64Response
	(*JsonFormatRequest)(nil),      // 6: privutil.JsonFormatRequest
	(*JsonFormatResponse)(nil),     // 7: privutil.JsonFormatResponse
	(*ConvertRequest)(nil),         // 8: privutil.ConvertRequest
	(*ConvertResponse)(nil),        // 9: privutil.ConvertResponse
	(*UuidRequest)(nil),            // 10: privutil.UuidRequest
	(*UuidResponse)(nil),           // 11: privutil.UuidResponse
	(*LoremRequest)(nil),           // 12: privutil.LoremRequest
	(*LoremResponse)(nil),          // 13: privutil.LoremResponse
	(*HashRequest)(nil),            // 14: privutil.HashRequest
	(*HashResponse)(nil),           // 15: privutil.HashResponse
	(*TextRequest)(nil),            // 16: privutil.TextRequest
	(*TextResponse)(nil),           // 17: privutil.TextResponse
	(*TimeRequest)(nil),            // 18: privutil.TimeRequest
	(*TimeResponse)(nil),           // 19: privutil.TimeResponse
	(*JwtRequest)(nil),             // 20: privutil.JwtRequest
	(*JwtResponse)(nil),            // 21: privutil.JwtResponse
	(*RegexRequest)(nil),           // 22: privutil.RegexRequest
	(*RegexResponse)(nil),          // 23: privutil.RegexResponse
	(*JsonToGoRequest)(nil),        // 24: privutil.JsonToGoRequest
	(*JsonToGoResponse)(nil),       // 25: privutil.JsonToGoResponse
	(*CronRequest)(nil),            // 26: privutil.CronRequest
	(*CronResponse)(nil),           // 27: privutil.CronResponse
	(*CertRequest)(nil),            // 28: privutil.CertRequest
	(*CertResponse)(nil),           // 29: privutil.CertResponse
	(*ColorRequest)(nil),           // 30: privutil.ColorRequest
	(*ColorResponse)(nil),          // 31: privutil.ColorResponse
	(*CaseRequest)(nil),            // 32: privutil.CaseRequest
	(*CaseResponse)(nil),           // 33: privutil.CaseResponse
	(*EscapeRequest)(nil),          // 34: privutil.EscapeRequest
	(*EscapeResponse)(nil),         // 35: privutil.EscapeResponse
	(*SimilarityRequest)(nil),      // 36: privutil.SimilarityRequest
	(*SimilarityResponse)(nil),     // 37: privutil.SimilarityResponse
	(*SqlRequest)(nil),             // 38: privutil.SqlRequest
	(*SqlResponse)(nil),            // 39: privutil.SqlResponse
	(*IpRequest)(nil),              // 40: privutil.IpRequest
	(*IpResponse)(nil),             // 41: privutil.IpResponse
	(*TextInspectRequest)(nil),     // 42: privutil.TextInspectRequest
	(*TextInspectResponse)(nil),    // 43: privutil.TextInspectResponse
	(*TextManipulateRequest)(nil),  // 44: privutil.TextManipulateRequest
	(*TextManipulateResponse)(nil), // 45: privutil.TextManipulateResponse
	(*PasswordRequest)(nil),        // 46: privutil.PasswordRequest
	(*PasswordResponse)(nil),       // 47: privutil.PasswordResponse
}
var file_proto_privutil_proto_depIdxs = []int32{
	0,  // 0: privutil.ConvertRequest.source_format:type_name -> privutil.DataFormat
	0,  // 1: privutil.ConvertRequest.target_format:type_name -> privutil.DataFormat
	1,  // 2: privutil.TextManipulateRequest.action:type_name -> privutil.TextAction
	2,  // 3: privutil.PrivUtilService.Diff:input_type -> privutil.DiffRequest
	4,  // 4: privutil.PrivUtilService.Base64Encode:input_type -> privutil.Base64Request
	4,  // 5: privutil.PrivUtilService.Base64Decode:input_type -> privutil.Base64Request
	6,  // 6: privutil.PrivUtilService.JsonFormat:input_type -> privutil.JsonFormatRequest
	8,  // 7: privutil.PrivUtilService.Convert:input_type -> privutil.ConvertRequest
	10, // 8: privutil.PrivUtilService.GenerateUuid:input_type -> privutil.UuidRequest
	12, // 9: privutil.PrivUtilService.GenerateLorem:input_type -> privutil.LoremRequest
	14, // 10: privutil.PrivUtilService.CalculateHash:input_type -> privutil.HashRequest
	42, // 11: privutil.PrivUtilService.TextInspect:input_type -> privutil.TextInspectRequest
	44, // 12: privutil.PrivUtilService.TextManipulate:input_type -> privutil.TextManipulateRequest
	16, // 13: privutil.PrivUtilService.UrlEncode:input_type -> privutil.TextRequest
	16, // 14: privutil.PrivUtilService.UrlDecode:input_type -> privutil.TextRequest
	16, // 15: privutil.PrivUtilService.HtmlEncode:input_type -> privutil.TextRequest
	16, // 16: privutil.PrivUtilService.HtmlDecode:input_type -> privutil.TextRequest
	18, // 17: privutil.PrivUtilService.TimeConvert:input_type -> privutil.TimeRequest
	20, // 18: privutil.PrivUtilService.JwtDecode:input_type -> privutil.JwtRequest
	22, // 19: privutil.PrivUtilService.RegexTest:input_type -> privutil.RegexRequest
	24, // 20: privutil.PrivUtilService.JsonToGo:input_type -> privutil.JsonToGoRequest
	26, // 21: privutil.PrivUtilService.CronExplain:input_type -> privutil.CronRequest
	28, // 22: privutil.PrivUtilService.CertParse:input_type -> privutil.CertRequest
	30, // 23: privutil.PrivUtilService.ColorConvert:input_type -> privutil.ColorRequest
	32, // 24: privutil.PrivUtilService.CaseConvert:input_type -> privutil.CaseRequest
	34, // 25: privutil.PrivUtilService.StringEscape:input_type -> privutil.EscapeRequest
	36, // 26: privutil.PrivUtilService.TextSimilarity:input_type -> privutil.SimilarityRequest
	38, // 27: privutil.PrivUtilService.SqlFormat:input_type -> privutil.SqlRequest
	40, // 28: privutil.PrivUtilService.IpCalc:input_type -> privutil.IpRequest
	46, // 29: privutil.PrivUtilService.GeneratePassword:input_type -> privutil.PasswordRequest
	3,  // 30: privutil.PrivUtilService.Diff:output_type -> privutil.DiffResponse
	5,  // 31: privutil.PrivUtilService.Base64Encode:output_type -> privutil.Base64Response
	5,  // 32: privutil.PrivUtilService.Base64Decode:output_type -> privutil.Base64Response
	7,  // 33: privutil.PrivUtilService.JsonFormat:output_type -> privutil.JsonFormatResponse
	9,  // 34: privutil.PrivUtilService.Convert:output_type -> privutil.ConvertResponse
	11, // 35: privutil.PrivUtilService.GenerateUuid:output_type -> privutil.UuidResponse
	13, // 36: privutil.PrivUtilService.GenerateLorem:output_type -> privutil.LoremResponse
	15, // 37: privutil.PrivUtilService.CalculateHash:output_type -> privutil.HashResponse
	43, // 38: privutil.PrivUtilService.TextInspect:output_type -> privutil.TextInspectResponse
	45, // 39: privutil.PrivUtilService.TextManipulate:output_type -> privutil.TextManipulateResponse
	17, // 40: privutil.PrivUtilService.UrlEncode:output_type -> privutil.TextResponse
	17, // 41: privutil.PrivUtilService.UrlDecode:output_type -> privutil.TextResponse
	17, // 42: privutil.PrivUtilService.HtmlEncode:output_type -> privutil.TextResponse
	17, // 43: privutil.PrivUtilService.HtmlDecode:output_type -> privutil.TextResponse
	19, // 44: privutil.PrivUtilService.TimeConvert:output_type -> privutil.TimeResponse
	21, // 45: privutil.PrivUtilService.JwtDecode:output_type -> privutil.JwtResponse
	23, // 46: privutil.PrivUtilService.RegexTest:output_type -> privutil.RegexResponse
	25, // 47: privutil.PrivUtilService.JsonToGo:output_type -> privutil.JsonToGoResponse
	27, // 48: privutil.PrivUtilService.CronExplain:output_type -> privutil.CronResponse
	29, // 49: privutil.PrivUtilService.CertParse:output_type -> privutil.CertResponse
	31, // 50: privutil.PrivUtilService.ColorConvert:output_type -> privutil.ColorResponse
	33, // 51: privutil.PrivUtilService.CaseConvert:output_type -> privutil.CaseResponse
	35, // 52: privutil.PrivUtilService.StringEscape:output_type -> privutil.EscapeResponse
	37, // 53: privutil.PrivUtilService.TextSimilarity:output_type -> privutil.SimilarityResponse
	39, // 54: privutil.PrivUtilService.SqlFormat:output_type -> privutil.SqlResponse
	41, // 55: privutil.PrivUtilService.IpCalc:output_type -> privutil.IpResponse
	47, // 56: privutil.PrivUtilService.GeneratePassword:output_type -> privutil.PasswordResponse
	30, // [30:57] is the sub-list for method output_type
	3,  // [3:30] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_privutil_proto_init() }
func file_proto_privutil_proto_init() {
	if File_proto_privutil_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_privutil_proto_rawDesc), len(file_proto_privutil_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   46,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_privutil_proto_goTypes,
		DependencyIndexes: file_proto_privutil_proto_depIdxs,
		EnumInfos:         file_proto_privutil_proto_enumTypes,
		MessageInfos:      file_proto_privutil_proto_msgTypes,
	}.Build()
	File_proto_privutil_proto = out.File
	file_proto_privutil_proto_goTypes = nil
	file_proto_privutil_proto_depIdxs = nil
}
