// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/privutil.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PrivUtilService_Diff_FullMethodName             = "/privutil.PrivUtilService/Diff"
	PrivUtilService_Base64Encode_FullMethodName     = "/privutil.PrivUtilService/Base64Encode"
	PrivUtilService_Base64Decode_FullMethodName     = "/privutil.PrivUtilService/Base64Decode"
	PrivUtilService_JsonFormat_FullMethodName       = "/privutil.PrivUtilService/JsonFormat"
	PrivUtilService_Convert_FullMethodName          = "/privutil.PrivUtilService/Convert"
	PrivUtilService_GenerateUuid_FullMethodName     = "/privutil.PrivUtilService/GenerateUuid"
	PrivUtilService_GenerateLorem_FullMethodName    = "/privutil.PrivUtilService/GenerateLorem"
	PrivUtilService_CalculateHash_FullMethodName    = "/privutil.PrivUtilService/CalculateHash"
	PrivUtilService_TextInspect_FullMethodName      = "/privutil.PrivUtilService/TextInspect"
	PrivUtilService_TextManipulate_FullMethodName   = "/privutil.PrivUtilService/TextManipulate"
	PrivUtilService_UrlEncode_FullMethodName        = "/privutil.PrivUtilService/UrlEncode"
	PrivUtilService_UrlDecode_FullMethodName        = "/privutil.PrivUtilService/UrlDecode"
	PrivUtilService_HtmlEncode_FullMethodName       = "/privutil.PrivUtilService/HtmlEncode"
	PrivUtilService_HtmlDecode_FullMethodName       = "/privutil.PrivUtilService/HtmlDecode"
	PrivUtilService_TimeConvert_FullMethodName      = "/privutil.PrivUtilService/TimeConvert"
	PrivUtilService_JwtDecode_FullMethodName        = "/privutil.PrivUtilService/JwtDecode"
	PrivUtilService_RegexTest_FullMethodName        = "/privutil.PrivUtilService/RegexTest"
	PrivUtilService_JsonToGo_FullMethodName         = "/privutil.PrivUtilService/JsonToGo"
	PrivUtilService_CronExplain_FullMethodName      = "/privutil.PrivUtilService/CronExplain"
	PrivUtilService_CertParse_FullMethodName        = "/privutil.PrivUtilService/CertParse"
	PrivUtilService_ColorConvert_FullMethodName     = "/privutil.PrivUtilService/ColorConvert"
	PrivUtilService_CaseConvert_FullMethodName      = "/privutil.PrivUtilService/CaseConvert"
	PrivUtilService_StringEscape_FullMethodName     = "/privutil.PrivUtilService/StringEscape"
	PrivUtilService_TextSimilarity_FullMethodName   = "/privutil.PrivUtilService/TextSimilarity"
	PrivUtilService_SqlFormat_FullMethodName        = "/privutil.PrivUtilService/SqlFormat"
	PrivUtilService_IpCalc_FullMethodName           = "/privutil.PrivUtilService/IpCalc"
	PrivUtilService_GeneratePassword_FullMethodName = "/privutil.PrivUtilService/GeneratePassword"
)

// PrivUtilServiceClient is the client API for PrivUtilService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PrivUtilServiceClient interface {
	Diff(ctx context.Context, in *DiffRequest, opts ...grpc.CallOption) (*DiffResponse, error)
	Base64Encode(ctx context.Context, in *Base64Request, opts ...grpc.CallOption) (*Base64Response, error)
	Base64Decode(ctx context.Context, in *Base64Request, opts ...grpc.CallOption) (*Base64Response, error)
	JsonFormat(ctx context.Context, in *JsonFormatRequest, opts ...grpc.CallOption) (*JsonFormatResponse, error)
	Convert(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*ConvertResponse, error)
	GenerateUuid(ctx context.Context, in *UuidRequest, opts ...grpc.CallOption) (*UuidResponse, error)
	GenerateLorem(ctx context.Context, in *LoremRequest, opts ...grpc.CallOption) (*LoremResponse, error)
	CalculateHash(ctx context.Context, in *HashRequest, opts ...grpc.CallOption) (*HashResponse, error)
	TextInspect(ctx context.Context, in *TextInspectRequest, opts ...grpc.CallOption) (*TextInspectResponse, error)
	TextManipulate(ctx context.Context, in *TextManipulateRequest, opts ...grpc.CallOption) (*TextManipulateResponse, error)
	UrlEncode(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*TextResponse, error)
	UrlDecode(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*TextResponse, error)
	HtmlEncode(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*TextResponse, error)
	HtmlDecode(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*TextResponse, error)
	TimeConvert(ctx context.Context, in *TimeRequest, opts ...grpc.CallOption) (*TimeResponse, error)
	JwtDecode(ctx context.Context, in *JwtRequest, opts ...grpc.CallOption) (*JwtResponse, error)
	RegexTest(ctx context.Context, in *RegexRequest, opts ...grpc.CallOption) (*RegexResponse, error)
	JsonToGo(ctx context.Context, in *JsonToGoRequest, opts ...grpc.CallOption) (*JsonToGoResponse, error)
	CronExplain(ctx context.Context, in *CronRequest, opts ...grpc.CallOption) (*CronResponse, error)
	CertParse(ctx context.Context, in *CertRequest, opts ...grpc.CallOption) (*CertResponse, error)
	ColorConvert(ctx context.Context, in *ColorRequest, opts ...grpc.CallOption) (*ColorResponse, error)
	CaseConvert(ctx context.Context, in *CaseRequest, opts ...grpc.CallOption) (*CaseResponse, error)
	StringEscape(ctx context.Context, in *EscapeRequest, opts ...grpc.CallOption) (*EscapeResponse, error)
	TextSimilarity(ctx context.Context, in *SimilarityRequest, opts ...grpc.CallOption) (*SimilarityResponse, error)
	SqlFormat(ctx context.Context, in *SqlRequest, opts ...grpc.CallOption) (*SqlResponse, error)
	IpCalc(ctx context.Context, in *IpRequest, opts ...grpc.CallOption) (*IpResponse, error)
	GeneratePassword(ctx context.Context, in *PasswordRequest, opts ...grpc.CallOption) (*PasswordResponse, error)
}

type privUtilServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPrivUtilServiceClient(cc grpc.ClientConnInterface) PrivUtilServiceClient {
	return &privUtilServiceClient{cc}
}

func (c *privUtilServiceClient) Diff(ctx context.Context, in *DiffRequest, opts ...grpc.CallOption) (*DiffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiffResponse)
	err := c.cc.Invoke(ctx, PrivUtilService_Diff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privUtilServiceClient) Base64Encode(ctx context.Context, in *Base64Request, opts ...grpc.CallOption) (*Base64Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Base64Response)
	err := c.cc.Invoke(ctx, PrivUtilService_Base64Encode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privUtilServiceClient) Base64Decode(ctx context.Context, in *Base64Request, opts ...grpc.CallOption) (*Base64Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Base64Response)
	err := c.cc.Invoke(ctx, PrivUtilService_Base64Decode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privUtilServiceClient) JsonFormat(ctx context.Context, in *JsonFormatRequest, opts ...grpc.CallOption) (*JsonFormatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonFormatResponse)
	err := c.cc.Invoke(ctx, PrivUtilService_JsonFormat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privUtilServiceClient) Convert(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*ConvertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConvertResponse)
	err := c.cc.Invoke(ctx, PrivUtilService_Convert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privUtilServiceClient) GenerateUuid(ctx context.Context, in *UuidRequest, opts ...grpc.CallOption) (*UuidResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UuidResponse)
	err := c.cc.Invoke(ctx, PrivUtilService_GenerateUuid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privUtilServiceClient) GenerateLorem(ctx context.Context, in *LoremRequest, opts ...grpc.CallOption) (*LoremResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoremResponse)
	err := c.cc.Invoke(ctx, PrivUtilService_GenerateLorem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privUtilServiceClient) CalculateHash(ctx context.Context, in *HashRequest, opts ...grpc.CallOption) (*HashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HashResponse)
	err := c.cc.Invoke(ctx, PrivUtilService_CalculateHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privUtilServiceClient) TextInspect(ctx context.Context, in *TextInspectRequest, opts ...grpc.CallOption) (*TextInspectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TextInspectResponse)
	err := c.cc.Invoke(ctx, PrivUtilService_TextInspect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privUtilServiceClient) TextManipulate(ctx context.Context, in *TextManipulateRequest, opts ...grpc.CallOption) (*TextManipulateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TextManipulateResponse)
	err := c.cc.Invoke(ctx, PrivUtilService_TextManipulate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privUtilServiceClient) UrlEncode(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*TextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TextResponse)
	err := c.cc.Invoke(ctx, PrivUtilService_UrlEncode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privUtilServiceClient) UrlDecode(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*TextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TextResponse)
	err := c.cc.Invoke(ctx, PrivUtilService_UrlDecode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privUtilServiceClient) HtmlEncode(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*TextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TextResponse)
	err := c.cc.Invoke(ctx, PrivUtilService_HtmlEncode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privUtilServiceClient) HtmlDecode(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*TextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TextResponse)
	err := c.cc.Invoke(ctx, PrivUtilService_HtmlDecode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privUtilServiceClient) TimeConvert(ctx context.Context, in *TimeRequest, opts ...grpc.CallOption) (*TimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimeResponse)
	err := c.cc.Invoke(ctx, PrivUtilService_TimeConvert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privUtilServiceClient) JwtDecode(ctx context.Context, in *JwtRequest, opts ...grpc.CallOption) (*JwtResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JwtResponse)
	err := c.cc.Invoke(ctx, PrivUtilService_JwtDecode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privUtilServiceClient) RegexTest(ctx context.Context, in *RegexRequest, opts ...grpc.CallOption) (*RegexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegexResponse)
	err := c.cc.Invoke(ctx, PrivUtilService_RegexTest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privUtilServiceClient) JsonToGo(ctx context.Context, in *JsonToGoRequest, opts ...grpc.CallOption) (*JsonToGoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonToGoResponse)
	err := c.cc.Invoke(ctx, PrivUtilService_JsonToGo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privUtilServiceClient) CronExplain(ctx context.Context, in *CronRequest, opts ...grpc.CallOption) (*CronResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CronResponse)
	err := c.cc.Invoke(ctx, PrivUtilService_CronExplain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privUtilServiceClient) CertParse(ctx context.Context, in *CertRequest, opts ...grpc.CallOption) (*CertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertResponse)
	err := c.cc.Invoke(ctx, PrivUtilService_CertParse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privUtilServiceClient) ColorConvert(ctx context.Context, in *ColorRequest, opts ...grpc.CallOption) (*ColorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ColorResponse)
	err := c.cc.Invoke(ctx, PrivUtilService_ColorConvert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privUtilServiceClient) CaseConvert(ctx context.Context, in *CaseRequest, opts ...grpc.CallOption) (*CaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaseResponse)
	err := c.cc.Invoke(ctx, PrivUtilService_CaseConvert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privUtilServiceClient) StringEscape(ctx context.Context, in *EscapeRequest, opts ...grpc.CallOption) (*EscapeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EscapeResponse)
	err := c.cc.Invoke(ctx, PrivUtilService_StringEscape_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privUtilServiceClient) TextSimilarity(ctx context.Context, in *SimilarityRequest, opts ...grpc.CallOption) (*SimilarityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimilarityResponse)
	err := c.cc.Invoke(ctx, PrivUtilService_TextSimilarity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privUtilServiceClient) SqlFormat(ctx context.Context, in *SqlRequest, opts ...grpc.CallOption) (*SqlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SqlResponse)
	err := c.cc.Invoke(ctx, PrivUtilService_SqlFormat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privUtilServiceClient) IpCalc(ctx context.Context, in *IpRequest, opts ...grpc.CallOption) (*IpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IpResponse)
	err := c.cc.Invoke(ctx, PrivUtilService_IpCalc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privUtilServiceClient) GeneratePassword(ctx context.Context, in *PasswordRequest, opts ...grpc.CallOption) (*PasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PasswordResponse)
	err := c.cc.Invoke(ctx, PrivUtilService_GeneratePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrivUtilServiceServer is the server API for PrivUtilService service.
// All implementations must embed UnimplementedPrivUtilServiceServer
// for forward compatibility.
type PrivUtilServiceServer interface {
	Diff(context.Context, *DiffRequest) (*DiffResponse, error)
	Base64Encode(context.Context, *Base64Request) (*Base64Response, error)
	Base64Decode(context.Context, *Base64Request) (*Base64Response, error)
	JsonFormat(context.Context, *JsonFormatRequest) (*JsonFormatResponse, error)
	Convert(context.Context, *ConvertRequest) (*ConvertResponse, error)
	GenerateUuid(context.Context, *UuidRequest) (*UuidResponse, error)
	GenerateLorem(context.Context, *LoremRequest) (*LoremResponse, error)
	CalculateHash(context.Context, *HashRequest) (*HashResponse, error)
	TextInspect(context.Context, *TextInspectRequest) (*TextInspectResponse, error)
	TextManipulate(context.Context, *TextManipulateRequest) (*TextManipulateResponse, error)
	UrlEncode(context.Context, *TextRequest) (*TextResponse, error)
	UrlDecode(context.Context, *TextRequest) (*TextResponse, error)
	HtmlEncode(context.Context, *TextRequest) (*TextResponse, error)
	HtmlDecode(context.Context, *TextRequest) (*TextResponse, error)
	TimeConvert(context.Context, *TimeRequest) (*TimeResponse, error)
	JwtDecode(context.Context, *JwtRequest) (*JwtResponse, error)
	RegexTest(context.Context, *RegexRequest) (*RegexResponse, error)
	JsonToGo(context.Context, *JsonToGoRequest) (*JsonToGoResponse, error)
	CronExplain(context.Context, *CronRequest) (*CronResponse, error)
	CertParse(context.Context, *CertRequest) (*CertResponse, error)
	ColorConvert(context.Context, *ColorRequest) (*ColorResponse, error)
	CaseConvert(context.Context, *CaseRequest) (*CaseResponse, error)
	StringEscape(context.Context, *EscapeRequest) (*EscapeResponse, error)
	TextSimilarity(context.Context, *SimilarityRequest) (*SimilarityResponse, error)
	SqlFormat(context.Context, *SqlRequest) (*SqlResponse, error)
	IpCalc(context.Context, *IpRequest) (*IpResponse, error)
	GeneratePassword(context.Context, *PasswordRequest) (*PasswordResponse, error)
	mustEmbedUnimplementedPrivUtilServiceServer()
}

// UnimplementedPrivUtilServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPrivUtilServiceServer struct{}

func (UnimplementedPrivUtilServiceServer) Diff(context.Context, *DiffRequest) (*DiffResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Diff not implemented")
}
func (UnimplementedPrivUtilServiceServer) Base64Encode(context.Context, *Base64Request) (*Base64Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Base64Encode not implemented")
}
func (UnimplementedPrivUtilServiceServer) Base64Decode(context.Context, *Base64Request) (*Base64Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Base64Decode not implemented")
}
func (UnimplementedPrivUtilServiceServer) JsonFormat(context.Context, *JsonFormatRequest) (*JsonFormatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JsonFormat not implemented")
}
func (UnimplementedPrivUtilServiceServer) Convert(context.Context, *ConvertRequest) (*ConvertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Convert not implemented")
}
func (UnimplementedPrivUtilServiceServer) GenerateUuid(context.Context, *UuidRequest) (*UuidResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateUuid not implemented")
}
func (UnimplementedPrivUtilServiceServer) GenerateLorem(context.Context, *LoremRequest) (*LoremResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateLorem not implemented")
}
func (UnimplementedPrivUtilServiceServer) CalculateHash(context.Context, *HashRequest) (*HashResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateHash not implemented")
}
func (UnimplementedPrivUtilServiceServer) TextInspect(context.Context, *TextInspectRequest) (*TextInspectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TextInspect not implemented")
}
func (UnimplementedPrivUtilServiceServer) TextManipulate(context.Context, *TextManipulateRequest) (*TextManipulateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TextManipulate not implemented")
}
func (UnimplementedPrivUtilServiceServer) UrlEncode(context.Context, *TextRequest) (*TextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UrlEncode not implemented")
}
func (UnimplementedPrivUtilServiceServer) UrlDecode(context.Context, *TextRequest) (*TextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UrlDecode not implemented")
}
func (UnimplementedPrivUtilServiceServer) HtmlEncode(context.Context, *TextRequest) (*TextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HtmlEncode not implemented")
}
func (UnimplementedPrivUtilServiceServer) HtmlDecode(context.Context, *TextRequest) (*TextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HtmlDecode not implemented")
}
func (UnimplementedPrivUtilServiceServer) TimeConvert(context.Context, *TimeRequest) (*TimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TimeConvert not implemented")
}
func (UnimplementedPrivUtilServiceServer) JwtDecode(context.Context, *JwtRequest) (*JwtResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JwtDecode not implemented")
}
func (UnimplementedPrivUtilServiceServer) RegexTest(context.Context, *RegexRequest) (*RegexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegexTest not implemented")
}
func (UnimplementedPrivUtilServiceServer) JsonToGo(context.Context, *JsonToGoRequest) (*JsonToGoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JsonToGo not implemented")
}
func (UnimplementedPrivUtilServiceServer) CronExplain(context.Context, *CronRequest) (*CronResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CronExplain not implemented")
}
func (UnimplementedPrivUtilServiceServer) CertParse(context.Context, *CertRequest) (*CertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CertParse not implemented")
}
func (UnimplementedPrivUtilServiceServer) ColorConvert(context.Context, *ColorRequest) (*ColorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ColorConvert not implemented")
}
func (UnimplementedPrivUtilServiceServer) CaseConvert(context.Context, *CaseRequest) (*CaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CaseConvert not implemented")
}
func (UnimplementedPrivUtilServiceServer) StringEscape(context.Context, *EscapeRequest) (*EscapeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StringEscape not implemented")
}
func (UnimplementedPrivUtilServiceServer) TextSimilarity(context.Context, *SimilarityRequest) (*SimilarityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TextSimilarity not implemented")
}
func (UnimplementedPrivUtilServiceServer) SqlFormat(context.Context, *SqlRequest) (*SqlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SqlFormat not implemented")
}
func (UnimplementedPrivUtilServiceServer) IpCalc(context.Context, *IpRequest) (*IpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IpCalc not implemented")
}
func (UnimplementedPrivUtilServiceServer) GeneratePassword(context.Context, *PasswordRequest) (*PasswordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GeneratePassword not implemented")
}
func (UnimplementedPrivUtilServiceServer) mustEmbedUnimplementedPrivUtilServiceServer() {}
func (UnimplementedPrivUtilServiceServer) testEmbeddedByValue()                         {}

// UnsafePrivUtilServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrivUtilServiceServer will
// result in compilation errors.
type UnsafePrivUtilServiceServer interface {
	mustEmbedUnimplementedPrivUtilServiceServer()
}

func RegisterPrivUtilServiceServer(s grpc.ServiceRegistrar, srv PrivUtilServiceServer) {
	// If the following call panics, it indicates UnimplementedPrivUtilServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PrivUtilService_ServiceDesc, srv)
}

func _PrivUtilService_Diff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivUtilServiceServer).Diff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivUtilService_Diff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivUtilServiceServer).Diff(ctx, req.(*DiffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivUtilService_Base64Encode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Base64Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivUtilServiceServer).Base64Encode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivUtilService_Base64Encode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivUtilServiceServer).Base64Encode(ctx, req.(*Base64Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivUtilService_Base64Decode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Base64Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivUtilServiceServer).Base64Decode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivUtilService_Base64Decode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivUtilServiceServer).Base64Decode(ctx, req.(*Base64Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivUtilService_JsonFormat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JsonFormatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivUtilServiceServer).JsonFormat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivUtilService_JsonFormat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivUtilServiceServer).JsonFormat(ctx, req.(*JsonFormatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivUtilService_Convert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivUtilServiceServer).Convert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivUtilService_Convert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivUtilServiceServer).Convert(ctx, req.(*ConvertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivUtilService_GenerateUuid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UuidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivUtilServiceServer).GenerateUuid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivUtilService_GenerateUuid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivUtilServiceServer).GenerateUuid(ctx, req.(*UuidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivUtilService_GenerateLorem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoremRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivUtilServiceServer).GenerateLorem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivUtilService_GenerateLorem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivUtilServiceServer).GenerateLorem(ctx, req.(*LoremRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivUtilService_CalculateHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivUtilServiceServer).CalculateHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivUtilService_CalculateHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivUtilServiceServer).CalculateHash(ctx, req.(*HashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivUtilService_TextInspect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextInspectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivUtilServiceServer).TextInspect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivUtilService_TextInspect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivUtilServiceServer).TextInspect(ctx, req.(*TextInspectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivUtilService_TextManipulate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextManipulateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivUtilServiceServer).TextManipulate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivUtilService_TextManipulate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivUtilServiceServer).TextManipulate(ctx, req.(*TextManipulateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivUtilService_UrlEncode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivUtilServiceServer).UrlEncode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivUtilService_UrlEncode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivUtilServiceServer).UrlEncode(ctx, req.(*TextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivUtilService_UrlDecode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivUtilServiceServer).UrlDecode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivUtilService_UrlDecode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivUtilServiceServer).UrlDecode(ctx, req.(*TextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivUtilService_HtmlEncode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivUtilServiceServer).HtmlEncode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivUtilService_HtmlEncode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivUtilServiceServer).HtmlEncode(ctx, req.(*TextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivUtilService_HtmlDecode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivUtilServiceServer).HtmlDecode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivUtilService_HtmlDecode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivUtilServiceServer).HtmlDecode(ctx, req.(*TextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivUtilService_TimeConvert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivUtilServiceServer).TimeConvert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivUtilService_TimeConvert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivUtilServiceServer).TimeConvert(ctx, req.(*TimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivUtilService_JwtDecode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JwtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivUtilServiceServer).JwtDecode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivUtilService_JwtDecode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivUtilServiceServer).JwtDecode(ctx, req.(*JwtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivUtilService_RegexTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivUtilServiceServer).RegexTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivUtilService_RegexTest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivUtilServiceServer).RegexTest(ctx, req.(*RegexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivUtilService_JsonToGo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JsonToGoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivUtilServiceServer).JsonToGo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivUtilService_JsonToGo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivUtilServiceServer).JsonToGo(ctx, req.(*JsonToGoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivUtilService_CronExplain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CronRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivUtilServiceServer).CronExplain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivUtilService_CronExplain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivUtilServiceServer).CronExplain(ctx, req.(*CronRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivUtilService_CertParse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivUtilServiceServer).CertParse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivUtilService_CertParse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivUtilServiceServer).CertParse(ctx, req.(*CertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivUtilService_ColorConvert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ColorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivUtilServiceServer).ColorConvert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivUtilService_ColorConvert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivUtilServiceServer).ColorConvert(ctx, req.(*ColorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivUtilService_CaseConvert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivUtilServiceServer).CaseConvert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivUtilService_CaseConvert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivUtilServiceServer).CaseConvert(ctx, req.(*CaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivUtilService_StringEscape_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EscapeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivUtilServiceServer).StringEscape(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivUtilService_StringEscape_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivUtilServiceServer).StringEscape(ctx, req.(*EscapeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivUtilService_TextSimilarity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimilarityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivUtilServiceServer).TextSimilarity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivUtilService_TextSimilarity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivUtilServiceServer).TextSimilarity(ctx, req.(*SimilarityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivUtilService_SqlFormat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SqlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivUtilServiceServer).SqlFormat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivUtilService_SqlFormat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivUtilServiceServer).SqlFormat(ctx, req.(*SqlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivUtilService_IpCalc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivUtilServiceServer).IpCalc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivUtilService_IpCalc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivUtilServiceServer).IpCalc(ctx, req.(*IpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivUtilService_GeneratePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivUtilServiceServer).GeneratePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivUtilService_GeneratePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivUtilServiceServer).GeneratePassword(ctx, req.(*PasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PrivUtilService_ServiceDesc is the grpc.ServiceDesc for PrivUtilService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PrivUtilService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "privutil.PrivUtilService",
	HandlerType: (*PrivUtilServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Diff",
			Handler:    _PrivUtilService_Diff_Handler,
		},
		{
			MethodName: "Base64Encode",
			Handler:    _PrivUtilService_Base64Encode_Handler,
		},
		{
			MethodName: "Base64Decode",
			Handler:    _PrivUtilService_Base64Decode_Handler,
		},
		{
			MethodName: "JsonFormat",
			Handler:    _PrivUtilService_JsonFormat_Handler,
		},
		{
			MethodName: "Convert",
			Handler:    _PrivUtilService_Convert_Handler,
		},
		{
			MethodName: "GenerateUuid",
			Handler:    _PrivUtilService_GenerateUuid_Handler,
		},
		{
			MethodName: "GenerateLorem",
			Handler:    _PrivUtilService_GenerateLorem_Handler,
		},
		{
			MethodName: "CalculateHash",
			Handler:    _PrivUtilService_CalculateHash_Handler,
		},
		{
			MethodName: "TextInspect",
			Handler:    _PrivUtilService_TextInspect_Handler,
		},
		{
			MethodName: "TextManipulate",
			Handler:    _PrivUtilService_TextManipulate_Handler,
		},
		{
			MethodName: "UrlEncode",
			Handler:    _PrivUtilService_UrlEncode_Handler,
		},
		{
			MethodName: "UrlDecode",
			Handler:    _PrivUtilService_UrlDecode_Handler,
		},
		{
			MethodName: "HtmlEncode",
			Handler:    _PrivUtilService_HtmlEncode_Handler,
		},
		{
			MethodName: "HtmlDecode",
			Handler:    _PrivUtilService_HtmlDecode_Handler,
		},
		{
			MethodName: "TimeConvert",
			Handler:    _PrivUtilService_TimeConvert_Handler,
		},
		{
			MethodName: "JwtDecode",
			Handler:    _PrivUtilService_JwtDecode_Handler,
		},
		{
			MethodName: "RegexTest",
			Handler:    _PrivUtilService_RegexTest_Handler,
		},
		{
			MethodName: "JsonToGo",
			Handler:    _PrivUtilService_JsonToGo_Handler,
		},
		{
			MethodName: "CronExplain",
			Handler:    _PrivUtilService_CronExplain_Handler,
		},
		{
			MethodName: "CertParse",
			Handler:    _PrivUtilService_CertParse_Handler,
		},
		{
			MethodName: "ColorConvert",
			Handler:    _PrivUtilService_ColorConvert_Handler,
		},
		{
			MethodName: "CaseConvert",
			Handler:    _PrivUtilService_CaseConvert_Handler,
		},
		{
			MethodName: "StringEscape",
			Handler:    _PrivUtilService_StringEscape_Handler,
		},
		{
			MethodName: "TextSimilarity",
			Handler:    _PrivUtilService_TextSimilarity_Handler,
		},
		{
			MethodName: "SqlFormat",
			Handler:    _PrivUtilService_SqlFormat_Handler,
		},
		{
			MethodName: "IpCalc",
			Handler:    _PrivUtilService_IpCalc_Handler,
		},
		{
			MethodName: "GeneratePassword",
			Handler:    _PrivUtilService_GeneratePassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/privutil.proto",
}
