name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6


    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: web/package-lock.json

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'
        check-latest: true

    - name: Build with Makefile
      run: make build
